import { Lora } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar";



const sunflower = Lora({
  subsets: ["latin"]
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-BR">
      <body
        className={`${sunflower.className} bg-gradient-to-b from-white to-green-50 `}
      >
        {/* <Navbar/> */}
        {children}
        <footer className="bg-gradient-to-b from-green-400 to-green-500 text-center flex justify-center">
          <div>
            <h2>IFRS - Campus Osório</h2>
            <p>Daniel dos Santos Chaves estudante de Análise e Desenvolvimento de Sistemas</p>
          </div>
        </footer>
      </body>
    </html>
  );
}
